Repository octokit/plugin-enterprise-compatibility.js, pull requests merged in 2023-06, with the labels that each got.

#388 Switch to esbuild
  package-lock.json
  package.json
  scripts/build.mjs
  src/index.ts
  test/octokit-rest.test.ts
  tsconfig.json
Labels: Type: Maintenance

#390 fix: revert the change to drop support for Node 14 & 16
  package.json
  scripts/build.mjs
Labels: Type: Bug, Priority: High

#383 ci: stop testing against NodeJS v14, v16
  .github/workflows/test.yml
  package.json
  scripts/build.mjs
Labels: Type: Breaking change, Type: Maintenance

#391 ci: add test job in workflow to not depend on specific Node versions
  .github/workflows/test.yml
Labels: Type: Maintenance

#398 docs: replace references to Skypack CDN with esm.sh
  README.md
Labels: Type: Documentation
